version: '3'
services:
  mysql-service:
    image: mysql:latest
    container_name: es51-database
    networks:
      - es51-network
    restart: always
    ports:
      - "51006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=busporto51
      - MYSQL_DATABASE=OPOBUS
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "10222"
    ports:
      - "51080:80"
    networks:
      - es51-network
    depends_on:
      - mysql-service
networks:
  es51-network:
    driver: bridge